package com.neocotic.wal.exception;

/**
 * Exception generated by wal.
 * 
 * @author Alasdair Mercer
 */
public class WalException extends RuntimeException
{

    /**
     * Constructs a new {@link WalException} with <tt>null</tt> as its detail message and cause.
     */
    public WalException()
    {
        super();
    }

    /**
     * Constructs a new {@link WalException} with the specified detail message and cause.
     * 
     * @param message the detail message
     * @param cause the cause
     */
    public WalException(String message, Throwable cause)
    {
        super(message, cause);
    }

    /**
     * Constructs a new {@link WalException} with the specified detail message and <tt>null</tt> as its cause.
     * 
     * @param message the detail message
     */
    public WalException(String message)
    {
        super(message);
    }

    /**
     * Constructs a new {@link WalException} with the specified cause and <tt>null</tt> as its detail message.
     * 
     * @param cause the cause
     */
    public WalException(Throwable cause)
    {
        super(cause);
    }
}